version: "3"
services:
  web:
    build: ./frontend
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
    ports:
      - "5011:5011"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      #- FLASK_APP=/usr/src/app/web_app.py
      - PYTHONUNBUFFERED=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
    command: gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:5011 wsgi:app --reload --no-sendfile
    #entrypoint:
    #  - flask
    #  - run
    #  - --host=0.0.0.0
    #  - --port=5011

