version: "3"
services:
  service_broker:
    build: ./frontend
    ports:
      - "5011:5011"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
    command: gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:5011 wsgi:app --reload --no-sendfile
    depends_on:
      - redis

  redis:
    container_name: redis
    image: arm32v7/redis
    ports:
      - "6380:6380"
    expose:
      - "6380"
    command: redis-server --port 6380
    restart: always
